GET http://localhost:8080/course?page=1&categories=PRODUCT_MANAGEMENT,WEB_DEVELOPMENT&username=testUser

###
GET http://localhost:8080/course/search?title=Java&username=testUser

###
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "username": "Dimas Suwono",
    "email": "DimasSuwono@Makanan.com",
    "password": "string"
}

###
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "Dimas Suwono",
  "password": "string"
}


###
GET http://localhost:8080/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJyb2dlciIsImlhdCI6MTcwMTM2NjYyNiwiZXhwIjoxNzAxMzg0NjI2fQ.APl7ncSdh_E9k_6NZ8EcNwiOhnqClarawYVlsN_C1imlV-zHjrkgW8VpMUk_mmgUKeVeCO0mN-2vYn1LCj_gqQ
